kwara_wards_map = {'abati alara': 'abati alara', 'aboto/odo-ode': 'aboto / odoode', 'adena': 'adena', 'adewole': 'adewole',
                    'afon': 'afon', 'agbeyangi': 'agbeyangi / gbadamu', 'agbona/fata': 'agbona / fata', 'agunjin': 'agwijin',
                    'ahogbada': 'aho', 'ayedun i': 'aiyedun', 'ajanaku': 'ajanaku / malete', 'ajase i': 'ajase 1',
                    'ajase ii': 'ajase 2', 'ajikobi': 'ajikobi', 'akanbi i': 'akanbi 1', 'akanbi ii': 'akanbi 2',
                    'akanbi iii': 'akanbi 3', 'akanbi iv': 'akanbi 4', 'akanbi v': 'akanbi 5', 'alanamu': 'alanamu',
                    'alla': 'alla', 'apado': 'apado', 'aran': 'aran', 'arandun': 'arandun',
                    'arobadi': 'arobadi', 'magaji are i': 'are 1', 'magaji are ii': 'are 2', 'babadudu': 'babadudu',
                    'baboko': 'baboko', 'badari': 'badari', 'awe/orimaro/adigbogbo': 'awe / orimaro', 'balogun': 'balogun',
                    'balogun fulani i': 'balogun fulani 1', 'balogun fulani ii': 'balogun fulani 2', 'balogun fulani iii': 'balogun fulani 3', 'bani': 'bani',
                    'bode saadu': 'bode saadu', 'bode/babane': 'bode babane', 'boriya/shiya': 'boriya / shiya', 'budo egba': 'budo-egba',
                    'bwen/kiyoru': 'bwen / kiyoru', 'edidi': 'edidi', 'efue/berikodo': 'efue / berikodo', 'ejidongari': 'egidogari',
                    'ekan': 'ekan', 'erin north': 'erin north', 'erin south': 'erin south', 'eruku': 'eruku',
                    'esie/ijan': 'esie-ijan', 'essa a': 'essa a', 'essa b': 'essa b', 'essa c': 'essa c',
                    'gambari ayekale': 'gambar / ayekale', 'gambari i': 'gambari 1', 'gambari ii': 'gambari 2', 'gure /giwasorio': 'yashikira 2',
                    'gwanabe i': 'gwanabe 1', 'gwanabe ii': 'gwanabe 2', 'gwanara': 'gwanara', 'gwaria': 'gwaria',
                    'ibagun': 'ibagun', 'idofian i': 'idofian 1', 'idofian ii': 'idofian 2', 'idofin igbona i': 'idofin / igbana 1',
                    'idofin igbona ii': 'idofin / igbana 2', 'idofin odo - ashe': 'idofin odoashe', 'ifaja': 'ifaja', 'igbaja i': 'igbaja 1',
                    'igbaja ii': 'igbaja 2', 'igbaja iii': 'igbaja 3', 'igbo-idun': 'igboidun', 'igbonna': 'igbomma',
                    'igosun': 'igosun', 'ihaye': 'ihaye', 'ijagbo': 'ijagbo', 'ijara': 'ijara',
                    'ikotun': 'ikotun-kwara', 'ila oja': 'ila- oja', 'ile ire': 'ile-ire', 'ilemona': 'ilemoma',
                    'ilesha': 'ilesha', 'iliale/imoji/erin-mope': 'ilale  / erin / imoji', 'iloffa': 'iloffa', 'egosi/imode': 'imade / egosi',
                    'ipee': 'ipee', 'ira': 'ipetu / rore / aran orin', 'iponrin': 'iponrin', 'bhc ilemona': 'ira',
                    'isanlu i': 'isanlu 1', 'isanlu ii': 'isanlu 2', 'isapa': 'isapa', 'iwo': 'iwo',
                    'jebba': 'jebba', 'jehunkunu': 'jeunkunu', 'kaiama i': 'kaiama 1', 'kaiama ii': 'kaiama 2',
                    'kaiama iii': 'kaiama 3', 'kemanji': 'kemaji', 'kenu/taberu': 'kenu / tabera', 'koro': 'koro',
                    'kpada i': 'kpada 1', 'kpada ii': 'kpada 2', 'kpada iii': 'kpada 3', 'kpura/yakira': 'kpura / yakiru',
                    'lade i': 'lade 1', 'lade ii': 'lade 2', 'lade iii': 'lade 3', 'laduba': 'laduba',
                    'lafiagi i': 'lafiagi 1', 'lafiagi ii': 'lafiagi 2', 'lafiagi iii': 'lafiagi 3', 'lafiagi iv': 'lafiagi 4',
                    'lanwa': 'lanwa', 'm/ngeri': 'm / ngeri', 'megidaa': 'magida', 'malete': 'malete',
                    'marafa/pepele': 'marafa / pepele', 'maya ile apa': 'maya / ileapa', 'obbo aiyegunle i': 'obbo-aiyegunle 1', 'obbo aiyegunle ii': 'obbo-aiyegunle 2',
                    'obbo-ile': 'obbo-ile', 'odo - owa i': 'odo-owa 1', 'odo - owa ii': 'odo-owa 2', 'ogbondoroko reke': 'ogbondoroko',
                    'ogele': 'ogele', 'ogidi': 'ogidi', 'ojoku': 'ojoku', 'ojomu ca': 'ojomo central a',
                    'ojomu cb': 'ojomo central b', 'ojomu nnw': 'ojomu north west', 'ojomu se': 'ojomu south east', 'zarumi/ojueku': 'oju-ekun',
                    'okaka i': 'okaka 1', 'okaka ii': 'okaka 2', 'oke aba': 'oke aba', 'oke ode i': 'oke-ode 1',
                    'oke ode ii': 'oke-ode 2', 'oke onigbin': 'oke onigbin', 'oke ode iii': 'oke-ode 3', 'oke-ogun': 'oka-ogun',
                    'oke-opin /etan': 'oke-opin / etan', 'oke-oyi/ oke ose': 'oke oyi / oke-ose / alalubosa', 'okemi': 'okemi', 'okeso': 'okeso',
                    'okeweru yowere ii': 'okeweru / yow 2', 'oko': 'oko', 'okoerin': 'oko-erin', 'okuta': 'okuta',
                    'okutala': 'okutala', 'olla': 'olla', 'oloje': 'oloje', 'oloru': 'oloru',
                    'omupo': 'omupo', 'onire/odegiwa': 'onire / odegiwa', 'opin': 'opin', 'ora': 'ora',
                    'oro i': 'oro 1', 'oro ii': 'oro 2', 'oro-ago': 'oro-ago', 'osi i': 'osi 1',
                    'osi ii': 'osi 2', 'otte/ballah': 'otte / ballah', 'owode/gbogun': 'owode / gbogun', 'owu': 'owu',
                    'pakunma': 'pakuma', 'pamo/oba/sabaja': 'sabaja / pama / oba', 'patigi i': 'pategi 1', 'patigi ii': 'pategi 2',
                    'patigi iii': 'pategi 3', 'patigi iv': 'pategi 4', 'shao': 'shao', 'share i': 'share 1',
                    'share ii': 'share 2', 'share iii': 'share 3', 'share iv': 'share 4', 'share v': 'share 5',
                    'shawo c': 'shawo central', 'shawo se': 'shawo south east', 'shawo sw': 'shawo south west', 'sinawu/tumbuyam': 'sinawu / tumbiya',
                    'sosoki/yowere': 'sosoki / yowere', 'tsaragi i': 'tsaragi 1', 'tsaragi ii': 'tsaragi 2', 'tsaragi iii': 'tsaragi 3',
                    'shonga i': 'tsonga 1', 'shonga ii': 'tsonga 2', 'shonga iii': 'tsonga 3', 'ubandawaki': 'ubandawaki',
                    'wara/osin/egbejila': 'wara / osin / egbejila', 'wojibe': 'wojibe', 'womi ayaki': 'womi ayaki', 'yashikira': 'yashikira 1',
                    }
kwara_lga_map = {'asa': 'asa', 'baruten': 'baruten', 'edu': 'edu', 'ekiti': 'ekiti', 'ifelodun': 'ifelodun',
                 'ilorin east': 'ilorin east', 'ilorin south': 'ilorin south', 'ilorin west': 'ilorin west', 
                 'irepodun': 'irepodun', 'isin': 'isin', 'kaiama': 'kaiama', 'moro': 'moro', 'offa': 'offa', 
                 'oke ero': 'oke ero', 'oyun': 'oyun', 'patigi': 'pategi'}

Ogun_lga_map = {'abeokuta north': 'abeokuta north', 'abeokuta south': 'abeokuta south',
                 'ado-odo ota': 'ado odo/ota', 'ewekoro': 'ewekoro', 'ifo': 'ifo', 
                 'ijebu east': 'ijebu east', 'ijebu north-east': 'ijebu north east',
                 'ijebu north': 'ijebu north',  'ijebu ode': 'ijebu ode', 
                 'ikenne': 'ikenne', 'imeko afon': 'imeko afon', 'ipokia': 'ipokia', 
                 'obafemi owode': 'obafemi owode', 'odeda': 'odeda', 'odogbolu': 'odogbolu', 
                 'ogun waterside': 'ogun waterside', 'remo north': 'remo north', 'sagamu': 'shagamu', 
                 'yewa north': 'yewa north', 'yewa south': 'yewa south'}

ogun_ward_map = {'iberekodo 1': 'iberekodo 1', 'iberekodo 2': 'iberekodo 2', 'iberekodo 3': 'iberekodo 3',
                'iberekodo 4': 'iberekodo 4', 'iberekodo 5': 'iberekodo 5', 'idiya': 'idiya', 
                'ikereku 1': 'ikereku 1', 'ikereku 2': 'ikereku 2', 'imala': 'imala', 'olorunda': 'olorunda',
                'sabo 1': 'sabo 1', 'sabo 2': 'sabo 2', 'totoro  4': 'totoro 4',   'totoro 1': 'totoro 1', 
                'totoro 2': 'totoro 2',  'totoro 3':'totoro 3','ake 1': 'ake 1', 'ake 2': 'ake 2', 
                'ake 3/abule oloni': 'ake 3', 'ibara 1': 'ibara 1',  'ibara 2': 'ibara 2', 
                'igbore agooba':'igbore / ago oba',   'ijaye':'ijaiye', 'ijeun titun': 'ijeun titun / ago-egun / ijesa',
                'imo/kuto':'kuto / imo / isabo',  'isale ijeun/iporo sodeke':'iporo / sodeke / sale-ijeun 1',  'itoko': 'itoko',
                'keesi emere':'emere', 'kemta agelende': 'kemta', 'oke ijemo':'ijemo', 'oke ijeun': 'oke ijeun', 
                'ado 2':'ado 2',  'ado1':'ado 1',  'agbara': 'agbara', 'alapoti': 'alapoti', 'atan': 'atan', 
                'ejila': 'ejila awori', 'ere': 'ere', 'igbesa': 'igbesa', 'ijoko': 'ijoko', 'iju': 'iju', 'ilogbo': 'ilogbo ward', 
                'ketu': 'ketu', 'ota 1': 'ota 1', 'ota 2': 'ota 2', 'ota 3': 'ota 3', 'sango': 'sango', 'abalabi': 'abalabi', 
                'arigbajo': 'arigbajo', 'asa/yobo': 'asayobo', 'elere/onigbedu': 'elere', 'itori': 'itori', 'mosan': 'mosan', 
                'obada oko': 'obada', 'owowo': 'owowo', 'papalanto': 'papa', 'wasimi': 'wasimi', 'agbado': 'agbado', 
                'agosi':'ifo 3', 'ajuwon/akute':'akute / ajuwon',  'ibogun': 'ibogun', 'ikorita/okenla': 'ifo 1', 
                'ilepa/coker': 'coker / ilepa', 'ojodu-isheri':'ojodu / isheri', 'oke aro/baragun': 'opeilu / ibaragun',
                'olose': 'ifo 2', 'oyero/ososun': 'ososun', 'sunren': 'sunren', 
                'ajebandele': 'ajebandele', 'ife 1': 'ife 1', 'ife 2': 'ife 2', 'ikija': 'ikija', 'imobi 1': 'imobi 1', 
                'imobi 2': 'imobi 2', 'imushin 1': 'imushin 1', 'imushin 2': 'imushin 2', 'itele': 'itele', 'ogbere': 'ogbere', 
                'owu': 'owu', 'igbeba': 'igbeba / erunwon', 'igede': 'igede', 'ilese': 'ilese', 'imewuro': 'imewuro', 
                'isoyin': 'isoyin', 'iworo': 'iworo / oju ona', 'oderegbe':'odosenlu',  'ogbogbo':'ogbogbo',  
                 'sembora':'odosenbora', 'ago iwoye 1': 'ago iwoye 1', 'ago iwoye 2': 'ago iwoye 2', 
                'akogelete': 'ako gelete', 'atikori': 'atikori', 'mamu': 'mamu', 'ojowo/japara': 'obada', 
                'oke-agbo': 'ojowo', 'oke-sopen/obada': 'oke agbo', 'omen': 'omen', 'oru/awa/ilaporu': 'oru / awa',
                'osun': 'osun', 'ijada/imepe': 'ijada / imepe 2', 'ijasi/idepo': 'ijasi / idepo', 
                'imupa/iyanro': 'imupa / iyanro / ijade / imepe 1', 'isiwo': 'isiwo', 'isoku/ososa': 'isoku / ososa', 
                'itamapako': 'itamapako', 'itantebu/ita-ogbin': 'itantebo / itaogbin', 'odo-egbo': 'odo-egbo / oliworo', 
                'odo-esa':'odo esa', 'porogun 1': 'porogun 1', 'porogun 2': 'porogun 2', 'ikenne 1': 'ikenne 1', 
                'ikenne 2': 'ikenne 2', 'ilisan 1': 'ilisan 1', 'ilisan 2': 'ilisan 2', 'iperu 1/iregun': 'iperu 1', 
                'iperu 2/imobido': 'iperu 2', 'iperu 3': 'iperu 3', 'irolu': 'irolu', 'ogere 1': 'ogere 1', 'ogere 2': 'ogere 2', 
                'afon': 'afon', 'agberiodo': 'agboriodo', 'agborogbomo': 'agborogbomo', 'atapele': 'atapele', 'idofa': 'idofa',
                'ilara': 'ilara', 'imeko': 'imeko', 'iwoye': 'iwoye', 'oke-agbede': 'matale', 'owode': 'owode',
                'agada': 'agada', 'agosasa': 'agosasa', 'ajegunle': 'ajegunle', 'idiroko': 'idiiroko', 'ifoyintedo': 'ifonyintedo', 
                'ihunbo/ilase': 'ihunbo ilashe', 'ijofin': 'ijofin', 'ipokia i': 'ipokia 1', 'ipokia ii': 'ipokia 2', 
                'maun 1': 'mahun 1', 'maun ii': 'mahun 2', 'tube': 'tube', 'ajebo': 'ajebo', 'ajura': 'ajura', 
                'alapako': 'alapako', 'egbeda': 'egbeda', 'kajola':'kajola',  'mokoloki':'molokiki',
                'moloko asipa':'maloko asipa',  'oba': 'oba', 'obafemi':'obafemi', 'ofada':'mowe', 'onidundu':'ibafo',
                'owode':'magboro', 'alabata': 'alabata', 'alagbagba': 'alagbagba', 'ilugun': 'ilugun', 'itesi': 'itesi', 
                'obantoko': 'obantoto', 'obete': 'obete', 'odeda': 'odeda', 'olodo': 'olodo', 'opeji': 'opebi', 
                'osiele': 'osiele', 'aiyepe eyinwa': 'itaepo', 'ala igbile':'igbile',  'ibefun': 'ibefun',  'ibido/ikise': 'ikise', 
                'idowa':'idowa',  'ilado/akio':'ilado', 'imodi': 'imodi',  'imosan': 'imosan', 'moraika-itaepo': 'moraika',
                 'odogbolu 1': 'odogbolu 1', 'odogbolu 2': 'odugbolu 2', 'ogbo': 'ogbo', 'okun owa': 'okun owa', 'omu': 'omu', 'ososa': 'ososa',
                 'abigi': 'abigi', 'ayede/lomiro': 'ayede', 'ayila': 'ayila', 'efire': 'efire', 'ibiade': 'ibiade', 'ilushin': 'ilushin', 
                 'iwopin':'iwopin 1', 'makun irokun': 'irokun', 'ode omi':'ode-omi',  'oni': 'iwopin 2', 'akaka': 'akaka', 'ilara': 'ilara', 
                 'ipara': 'ipara', 'isara 1': 'isara 1', 'isara 2': 'isara 2', 'isara 3': 'isara 3', 'iyankan/magbon': 'iyankan / imagbon', 
                 'ode 1': 'ode 1', 'ode 2': 'ode 2', 'orile oko': 'orile oko','agbowa/ibido': 'agbowa','soyindo':'soyindo',
                'ajaka':'ajara',
                 'ayegbami':'ayegbami',  'ijagba':'ijagba',  'isote': 'isote', 'itunsokun':'itunsoku',  
                 'latawa':'latawa',  'odelemo':'odelemo',  'ogijo': 'ogijo', 'ojumele':'ojumele',  'sabo agura': 'agura / sabo 2', 
                 'simawa':'simawa', 'sabo gra':'gra sabo', 'batoro /ado':'batoro /ado',
                 'ayetoro 1(idofoi)':'idofoi',   'ayetoro 2(isa ope)': 'ayetoro 2', 'ayetoro 3(ibile)':'ayetoro 1',  
                 'ebute':'ebute',  'eggua':'eggua', 'igbogila': 'igbogila / ibese', 'ijoun': 'ijoun', 'imasai': 'imasayi', 
                 'joga': 'joga / iboro', 'ohunbe': 'ohunbe', 'sunwa': 'sunwa', 'ajilete': 'ajilete', 'idogo': 'idogo', 
                 'ilaro 1': 'ilaro 1', 'ilaro 2': 'ilaro 2', 'ilaro 3': 'ilaro 3', 'ilobi/erinja': 'ilobi / erinja', 
                 'iwoye': 'iwoye', 'oke-odan': 'oke odan', 'owode 1': 'owode 1', 'owode 2': 'owode 2'}
 

kwara_security_challenged ={"Baruten":["Yashikira",'Gure /Giwasorio'],"Edu":["Lafiagi II", "Lafiagi III"],
                            "Oke Ero":["Idofin Odo - Ashe", "Idofin Igbona II","Idofin Igbona I"],
                            "Isin":["Olla","Isanlu I","Isanlu II","Owu"], 
                            "Irepodun":["Ajase I","Ajase II","Arandun","Oro I","Esie/Ijan"],
                            "Ekiti":["Koro","Eruku","Isapa","Obbo-Ile","Obbo Aiyegunle I","Obbo Aiyegunle II"],
                            "Oyun":["Ahogbada","Igbonna","Ikotun","Ojoku","BHC ILEMONA"],
                            "Moro":["Babadudu","Bode Saadu","Ejidongari","Jehunkunu","Megida","Shao"]
                            }


wards_shapefile ="Nigeria Wards/Nigeria_Wards.shp"
set_extent_shapefile = "Nigeria_Settlement_Extents_Version_02/nga_stlext_grid3_v02.shp"
lga_shapefile = "Nigeria_-_Local_Government_Area_Boundaries/Nigeria_-_Local_Government_Area_Boundaries.shp"