
# giving the difference in the name of wards and lga between GRID3 data set and p3b tempate
# This dictionaries were create to fix this issues
# if the state of interest is not here create one for that state below using this format
kwara_lga_map = {'asa': 'asa', 'baruten': 'baruten', 'edu': 'edu', 'ekiti': 'ekiti', 'ifelodun': 'ifelodun',
                 'ilorin east': 'ilorin east', 'ilorin south': 'ilorin south', 'ilorin west': 'ilorin west', 
                 'irepodun': 'irepodun', 'isin': 'isin', 'kaiama': 'kaiama', 'moro': 'moro', 'offa': 'offa', 
                 'oke ero': 'oke ero','oke-ero':'oke ero', 'oyun': 'oyun', 'patigi': 'pategi','pategi': 'pategi'}
ogun_lga_map = {'abeokuta north': 'abeokuta north', 'abeokuta south': 'abeokuta south',
                 'ado-odo ota': 'ado odo/ota', 'ewekoro': 'ewekoro', 'ifo': 'ifo', 
                 'ijebu east': 'ijebu east', 'ijebu north-east': 'ijebu north east',
                 'ijebu north': 'ijebu north',  'ijebu ode': 'ijebu ode', 
                 'ikenne': 'ikenne', 'imeko afon': 'imeko afon', 'ipokia': 'ipokia', 
                 'obafemi owode': 'obafemi owode', 'odeda': 'odeda', 'odogbolu': 'odogbolu', 
                 'ogun waterside': 'ogun waterside', 'remo north': 'remo north', 'sagamu': 'shagamu', 
                 'yewa north': 'yewa north', 'yewa south': 'yewa south'}

jigawa_lga_map = {'auyo': 'auyo', 'babura': 'babura', 'birnin kudu': 'birnin kudu',  'birniwa': 'biriniwa',
            'buji': 'buji', 'dutse': 'dutse', 'gagarawa': 'gagarawa', 'garki': 'garki', 'gumel': 'gumel',
            'guri': 'guri', 'gwaram': 'gwaram', 'gwiwa': 'gwiwa', 'hadejia': 'hadejia', 'jahun': 'jahun',
            'kafin hausa': 'kafin hausa', 'kaugama': 'kaugama', 'kazaure': 'kazaure', 'kiri kasamma': 'kiri kasama',
            'kiyawa': 'kiyawa', 'maigatari': 'maigatari', 'mallam maduri': 'malam madori', 'miga': 'miga',
            'ringim': 'ringim', 'roni': 'roni', 'sule tankakar': 'sule tankarkar', 'taura': 'taura', 'yankwashi': 'yankwashi'}
ogun_wards_map = {'abeokuta north': {'totoro 3': 'totoro 3', 'iberekodo 3': 'iberekodo 3', 
                                    'iberekodo 1': 'iberekodo 1', 'iberekodo 2': 'iberekodo 2', 
                                    'totoro  4': 'totoro 4', 'totoro 1': 'totoro 1', 'sabo 1': 'sabo 1', 
                                    'totoro 2': 'totoro 2', 'ikereku 1': 'ikereku 1', 'ikereku 2': 'ikereku 2', 
                                    'iberekodo 4': 'iberekodo 4', 'olorunda': 'olorunda', 'iberekodo 5': 'iberekodo 5', 
                                    'imala': 'imala', 'sabo 2': 'sabo 2', 'idiya': 'idiya'},
                'abeokuta south': {'ibara 1': 'ibara 1', 'ake 2': 'ake 2', 'ijaye': 'ijaiye', 'itoko': 'itoko', 
                                   'imo/kuto': 'kuto / imo / isabo', 'kemta agelende': 'kemta', 'oke ijemo': 'ijemo', 
                                   'ibara 2': 'ibara 2', 'igbore agooba': 'igbore / ago oba', 
                                   'ijeun titun': 'ijeun titun / ago-egun / ijesa', 'keesi emere': 'emere', 
                                   'oke ijeun': 'oke ijeun', 'ake 3/abule oloni': 'ake 3', 
                                   'isale ijeun/iporo sodeke': 'iporo / sodeke / sale-ijeun 1'},
                'ado-odo ota': {'alapoti': 'alapoti', 'ado 2': 'ado 2', 'ado1': 'ado 1', 'ere': 'ere', 'ketu': 'ketu', 
                                'ota 2': 'ota 2', 'igbesa': 'igbesa', 'ilogbo': 'ilogbo ward', 'agbara': 'agbara', 
                                'atan': 'atan ward', 'ejila': 'ejila awori', 'ota 1': 'ota 1', 'ota 3': 'ota 3', 
                                'ijoko': 'ijoko', 'iju': 'iju', 'sango': 'sango'},
                'ewekoro': {'mosan': 'mosan', 'abalabi': 'abalabi', 'asa/yobo': 'asayobo', 'owowo': 'owowo', 
                            'elere/onigbedu': 'elere', 'arigbajo': 'arigbajo', 'papalanto': 'papa', 'wasimi': 'wasimi', 
                            'obada oko': 'obada', 'itori': 'itori'},
                'ifo': {'sunren': 'sunren', 'ikorita/okenla': 'ifo 1', 'ibogun': 'ibogun', 'agosi': 'ifo 3', 
                        'oyero/ososun': 'ososun', 'olose': 'ifo 2', 'ojodu-isheri': 'ojodu / isheri', 
                        'ilepa/coker': 'coker / ilepa', 'ajuwon/akute': 'akute / ajuwon', 'agbado': 'agbado', 
                        'oke aro/baragun': 'opeilu / ibaragun'},
                        'ijebu east': {'ikija': 'ikija', 'imobi 1': 'imobi 1', 'imobi 2': 'imobi 2', 'itele': 'itele', 
                                       'ife 2': 'ife 2', 'imushin 1': 'imushin 1', 'ife 1': 'ife 1', 'imushin 2': 'imushin 2', 
                                       'ogbere': 'ogbere', 'owu': 'owu', 'ajebandele': 'ajebandele'},
                'ijebu north-east': {'oderegbe': 'odosenlu', 'iworo': 'iworo / oju ona', 'igede': 'igede', 'atan': 'atan', 
                                     'isoyin': 'isoyin', 'sembora': 'odosenbora', 'igbeba': 'igbeba / erunwon', 
                                     'imewuro': 'imewuro', 'ilese': 'ilese', 'ogbogbo': 'ogbogbo'},
                'ijebu north': {'akogelete': 'ako gelete', 'mamu': 'mamu', 'ago iwoye 1': 'ago iwoye 1', 
                                'ojowo/japara': 'obada', 'ago iwoye 2': 'ago iwoye 2', 'osun': 'osun', 
                                'oru/awa/ilaporu': 'oru / awa', 'oke-agbo': 'ojowo', 'oke-sopen/obada': 'oke agbo', 
                                'atikori': 'atikori', 'omen': 'omen'},
                'ijebu ode': {'isiwo': 'isiwo', 'itamapako': 'itamapako', 'itantebu/ita-ogbin': 'itantebo / itaogbin', 
                              'imupa/iyanro': 'imupa / iyanro / ijade / imepe 1', 'isoku/ososa': 'isoku / ososa', 
                              'porogun 1': 'porogun 1', 'odo-egbo': 'odo-egbo / oliworo', 'porogun 2': 'porogun 2', 
                              'ijasi/idepo': 'ijasi / idepo', 'ijada/imepe': 'ijada / imepe 2', 'odo-esa': 'odo esa'},
                'ikenne': {'irolu': 'irolu', 'iperu 1/iregun': 'iperu 1', 'iperu 2/imobido': 'iperu 2', 'ogere 1': 'ogere 1', 
                           'ogere 2': 'ogere 2', 'ikenne 1': 'ikenne 1', 'ilisan 2': 'ilisan 2', 'ilisan 1': 'ilisan 1', 
                           'iperu 3': 'iperu 3', 'ikenne 2': 'ikenne 2'},
                'imeko afon': {'idofa': 'idofa', 'agborogbomo': 'agborogbomo', 'atapele': 'atapele', 'agberiodo': 'agboriodo', 
                               'afon': 'afon', 'oke-agbede': 'matale', 'iwoye': 'iwoye', 'ilara': 'ilara', 'owode': 'owode', 
                               'imeko': 'imeko'},
                'ipokia': {'agada': 'agada', 'maun ii': 'mahun 2', 'ijofin': 'ijofin', 'maun 1': 'mahun 1', 'ipokia i': 'ipokia 1',
                            'ajegunle': 'ajegunle', 'tube': 'tube', 'ipokia ii': 'ipokia 2', 'ihunbo/ilase': 'ihunbo ilashe', 
                            'agosasa': 'agosasa', 'ifoyintedo': 'ifonyintedo', 'idiroko': 'idiiroko'},
                'obafemi owode': {'onidundu': 'onidundu', 'moloko asipa': 'maloko asipa', 'kajola': 'kajola', 'alapako': 'alapako',
                                   'obafemi': 'obafemi', 'mokoloki': 'molokiki', 'ajura': 'ajura', 'ajebo': 'ajebo', 
                                   'egbeda': 'egbeda', 'owode': 'owode', 'oba': 'oba', 'ofada': 'ofada'},
                'odeda': {'itesi': 'itesi', 'obete': 'obete', 'olodo': 'olodo', 'alagbagba': 'alagbagba', 'osiele': 'osiele', 
                          'alabata': 'alabata', 'opeji': 'opebi', 'ilugun': 'ilugun', 'odeda': 'odeda', 'obantoko': 'obantoto'},
                'odogbolu': {'ilado/akio': 'ilado', 'ibido/ikise': 'ikise', 'imosan': 'imosan', 'ala igbile': 'igbile', 
                             'idowa': 'idowa', 'odogbolu 1': 'odogbolu 1', 'omu': 'omu', 'ibefun': 'ibefun', 'ogbo': 'ogbo', 
                             'odogbolu 2': 'odugbolu 2', 'imodi': 'imodi', 'aiyepe eyinwa': 'itaepo', 'okun owa': 'okun owa', 
                             'ososa': 'ososa', 'moraika-itaepo': 'moraika'},
                'ogun waterside': {'efire': 'efire', 'abigi': 'abigi', 'ayila': 'ayila', 'makun irokun': 'irokun', 
                                'ayede/lomiro': 'ayede', 'oni': 'iwopin 2', 'ode omi': 'ode-omi', 'ilushin': 'ilushin', 
                                'ibiade': 'ibiade', 'iwopin': 'iwopin 1'},
                'remo north': {'iyankan/magbon': 'iyankan / imagbon', 'ilara': 'ilara', 'akaka': 'akaka', 'isara 2': 'isara 2', 
                               'ode 2': 'ode 2', 'isara 3': 'isara 3', 'ipara': 'ipara', 'ode 1': 'ode 1', 'orile oko': 'orile oko', 
                               'isara 1': 'isara 1'},
                'sagamu': {'ogijo': 'ogijo', 'isote': 'isote', 'agbowa/ibido': 'agbowa', 'odelemo': 'odelemo', 'latawa': 'latawa', 
                           'ijagba': 'ijagba', 'sonyido': 'soyindo / oko / epe / itula 1', 'simawa': 'simawa', 'ojumele': 'ojumele', 
                           'sabo gra': 'gra sabo', 'ayegbami': 'ayegbami', 'itunsokun': 'itunsoku', 'ajaka': 'ajara', 
                           'sabo agura': 'agura / sabo 2', 'batoro /ado': 'batoro /ado'},
                'yewa north': {'joga': 'joga / iboro', 'eggua': 'eggua', 'imasai': 'imasayi', 'ijoun': 'ijoun', 
                                'ayetoro 2(isa ope)': 'ayetoro 2', 'ayetoro 3(ibile)': 'ayetoro 1', 'ohunbe': 'ohunbe', 
                                'igbogila': 'igbogila / ibese', 'sunwa': 'sunwa', 'ayetoro 1(idofoi)': 'idofoi', 'ebute': 'ebute'},
                'yewa south': {'ilaro 2': 'ilaro 2', 'iwoye': 'iwoye', 'ajilete': 'ajilete', 'ilaro 3': 'ilaro 3', 'idogo': 'idogo', 
                               'ilobi/erinja': 'ilobi / erinja', 'ilaro 1': 'ilaro 1', 'owode 1': 'owode 1', 'oke-odan': 'oke odan', 
                               'owode 2': 'owode 2'}
                }

kwara_wards_map = {'asa': {'okeso': 'okeso', 'okesho': 'okeso','sosoki/yowere': 'sosoki / yowere', 'okeweru yowere ii': 'okeweru / yow 2', 
                           'ogbondoroko reke': 'ogbondoroko', 'awe/orimaro/adigbogbo': 'awe / orimaro', 'elebue awe/orimaro':'awe / orimaro',
                           'owode/gbogun': 'owode / gbogun', 'aboto/odo-ode': 'aboto / odoode', 'aboto':'aboto / odoode','agbona/fata': 'agbona / fata', 
                           'efue/berikodo': 'efue / berikodo', 'gambari ayekale': 'gambar / ayekale', 
                           'onire/odegiwa': 'onire / odegiwa', 'afon': 'afon', 'budo egba': 'budo-egba', 'ogele': 'ogele', 
                           'ila oja': 'ila- oja', 'laduba': 'laduba', 'otte/ballah': 'otte / ballah'},
                    'baruten': {'bode/babane': 'bode babane', 'sinawu/tumbuyam': 'sinawu / tumbiya', 'sinawu/tumbiya': 'sinawu / tumbiya',
                                'kpura/yakira': 'kpura / yakiru', 'kpura/yakiru':'kpura / yakiru',
                                'gwanara': 'gwanara', 'kenu/taberu': 'kenu / tabera','kenu/tabera': 'kenu / tabera', 'ilesha': 'ilesha', 'bwen/kiyoru': 'bwen / kiyoru', 
                                'yashikira': 'yashikira 1', 'boriya/shiya': 'boriya / shiya', 'okuta': 'okuta', 
                                'gure /giwasorio': 'yashikira 2', 'gure/giwasorio': 'yashikira 2'},
                    'edu': {'shonga iii': 'tsonga 3', 'tsonga iii': 'tsonga 3', 'shonga i': 'tsonga 1', 'tsonga i': 'tsonga 1', 'shonga ii': 'tsonga 2', 'tsonga ii':'tsonga 2', 'tsaragi iii': 'tsaragi 3', 
                            'tsaragi i': 'tsaragi 1', 'lafiagi i': 'lafiagi 1', 'lafiagi iii': 'lafiagi 3', 'lafiagi ii': 'lafiagi 2', 
                            'tsaragi ii': 'tsaragi 2', 'lafiagi iv': 'lafiagi 4'},
                    'ekiti': {'isapa': 'isapa', 'obbo aiyegunle i': 'obbo-aiyegunle 1', 'koro': 'koro', 'eruku': 'eruku', 'eruku i': 'eruku', 'obbo-ile': 'obbo-ile', 
                              'oke-opin /etan': 'oke-opin / etan', 'oke-opin/etan':'oke-opin / etan', 'obbo aiyegunle ii': 'obbo-aiyegunle 2', 'osi ii': 'osi 2', 'osi i': 'osi 1', 
                              'opin': 'opin'},
                    'ifelodun': {'oke ode iii': 'oke-ode 3', 'share i': 'share 1', 'share ii': 'share 2', 'igbaja ii': 'igbaja 2', 
                                 'share iv': 'share 4', 'oke ode i': 'oke-ode 1', 'share iii': 'share 3', 'agunjin': 'agwijin', 
                                 'ora': 'ora', 'igbaja iii': 'igbaja 3', 'igbaja i': 'igbaja 1', 'idofian i': 'idofian 1', 'share v': 'share 5', 
                                 'oro-ago': 'oro-ago', 'oke ode ii': 'oke-ode 2', 'omupo': 'omupo', 'ile ire': 'ile-ire', 'idofian ii': 'idofian 2'},
                    'ilorin east': {'iponrin': 'iponrin', 'apado': 'apado', 'agbeyangi': 'agbeyangi / gbadamu', 'marafa/ pepele': 'marafa / pepele',
                                    'marafa/pepele':'marafa / pepele', 'oke-oyi/oke ose': 'oke oyi / oke-ose / alalubosa',
                                    'maya ile apa': 'maya / ileapa', 'zango': 'zango 1', 'gambari ii': 'gambari 2', 
                                    'oke-oyi/ oke ose': 'oke oyi / oke-ose / alalubosa', 'magaji are ii': 'are 2', 'magaji are i': 'are 1', 
                                    'gambari i': 'gambari 1', 'ibagun': 'ibagun'},
                    'ilorin south': {'akanbi i': 'akanbi 1', 'akanbi ii': 'akanbi 2', 'balogun fulani i': 'balogun fulani 1', 'okaka i': 'okaka 1',
                                      'balogun fulani ii': 'balogun fulani 2', 'okaka ii': 'okaka 2', 'oke-ogun': 'oka-ogun', 
                                      'balogun fulani iii': 'balogun fulani 3', 'akanbi iii': 'akanbi 3', 'akanbi iv': 'akanbi 4', 
                                      'akanbi v': 'akanbi 5'},
                    'ilorin west': {'baboko': 'baboko', 'badari ward': 'badari', 'badari': 'badari', 'oloje': 'oloje', 'ogidi': 'ogidi', 'm/ngeri': 'm / ngeri', 
                                    'zarumi/ojueku': 'oju-ekun', 'ajikobi': 'ajikobi', 'ubandawaki': 'ubandawaki', 'adewole': 'adewole', 
                                    'alanamu': 'alanamu', 'okoerin': 'oko-erin', 'wara/osin/egbejila': 'wara / osin / egbejila'},
                    'irepodun': {'ifaja': 'ifaja', 'oko': 'oko', 'esie/ijan': 'esie-ijan', 'aran': 'aran', 'oro i': 'oro 1', 'arandun': 'arandun', 
                                 'oro ii': 'oro 2', 'ajase i': 'ajase 1', 'ihaye': 'ihaye', 'ira': 'ipetu / rore / aran orin', 'ipetu/rore/aran orin':'ipetu / rore / aran orin',
                                 'ajase ii': 'ajase 2'},
                    'isin': {'olla': 'olla', 'iwo': 'iwo', 'pamo/oba/sabaja': 'sabaja / pama / oba', 'owu': 'owu', 'edidi': 'edidi', 
                             'alla': 'alla', 'ijara': 'ijara', 'oke aba': 'oke aba', 'oke oba':'oke aba','isanlu ii': 'isanlu 2', 'isanlu i': 'isanlu 1', 
                             'oke onigbin': 'oke onigbin'},
                    'kaiama': {'kaiama iii': 'kaiama 3', 'kaiama i': 'kaiama 1', 'gwanabe ii': 'gwanabe 2', 'gwaria': 'gwaria', 
                               'gwanabe i': 'gwanabe 1', 'wojibe': 'wojibe', 'kemanji': 'kemaji', 'kaiama ii': 'kaiama 2', 'bani': 'bani', 
                               'adena': 'adena'},
                    'moro': {'womi ayaki': 'womi ayaki', 'lanwa': 'lanwa', 'okemi': 'okemi', 'pakunma': 'pakuma', 'megida': 'magida', 'megidaa':'magida', 
                             'arobadi': 'arobadi', 'babadudu': 'babadudu', 'ajanaku': 'ajanaku / malete', 'malete': 'malete', 
                             'shao': 'shao', 'jehunkunu': 'jeunkunu', 'okutala': 'okutala', 'bode saadu': 'bode saadu', 'ejidongari': 'egidogari', 
                             'jebba': 'jebba', 'abati alara': 'abati alara', 'oloru': 'oloru'},
                    'offa': {'essa b': 'essa b', 'essa a': 'essa a', 'balogun': 'balogun', 'igbo-idun': 'igboidun', 'ojomu se': 'ojomu south east', 
                             'ojomu cb': 'ojomo central b', 'shawo se': 'shawo south east','shawo south east':'shawo south east', 'ojomu south east':'ojomu south east', 'shawo sw': 'shawo south west', 
                             'ojomu nnw': 'ojomu north west', 'ojomu north west': 'ojomu north west','ojomo central b':'ojomo central b','shawo south west':'shawo south west',
                             'shawo c': 'shawo central', 'shawo central':'shawo central', 'ojomu ca': 'ojomo central a', 'ojomo central a':'ojomo central a', 'essa c': 'essa c'},
                    'oke ero': {'egosi/imode': 'imade / egosi', 'iliale/imoji/erin-mope': 'ilale  / erin / imoji', 'idofin igbona ii': 'idofin / igbana 2', 
                                'idofin igbona i': 'idofin / igbana 1', 'odo - owa i': 'odo-owa 1', 'odo - owa ii': 'odo-owa 2', 'idofin odo - ashe': 'idofin odoashe',
                                'iloffa': 'iloffa', 'ekan': 'ekan', 'ayedun i': 'aiyedun'},
                    'oke-ero': {'egosi/imode': 'imade / egosi', 'imade/egosi':'imade / egosi', 'iliale/imoji/erin-mope': 'ilale  / erin / imoji', 'idofin igbona ii': 'idofin / igbana 2', 
                                'idofin igbona i': 'idofin / igbana 1', 'odo - owa i': 'odo-owa 1', 'odo - owa ii': 'odo-owa 2', 'idofin odo - ashe': 'idofin odoashe',
                                'iloffa': 'iloffa', 'ekan': 'ekan', 'ayedun i': 'aiyedun','aiyedun':'aiyedun',},
                    'oyun': {'ahogbada': 'aho', 'ilemona': 'ilemoma', 'igbonna': 'igbomma','igbomma': 'igbomma', 'igosun': 'igosun', 'ikotun': 'ikotun-kwara', 'ipee': 'ipee', 
                             'ojoku': 'ojoku', 'bhc ilemona': 'ira', 'ira':'ira', 'ijagbo': 'ijagbo', 'erin south': 'erin south', 'erin north': 'erin north'},
                    'patigi': {'patigi iii': 'pategi 3', 'patigi i': 'pategi 1', 'patigi ii': 'pategi 2', 'kpada iii': 'kpada 3', 'lade i': 'lade 1', 
                               'kpada i': 'kpada 1', 'patigi iv': 'pategi 4', 'lade ii': 'lade 2', 'lade iii': 'lade 3', 'kpada ii': 'kpada 2'}
                    }

jigawa_wards_map = {
                        'auyo': {'tsidir': 'tsidir', 'gatafa': 'gatafa', 'kafur': 'kafur', 'ayan': 'ayan', 'auyakawa': 'auyakayi', 
                             'gamafoi': 'gamafoi', 'ayama': 'ayama', 'gamsarka': 'gamsarka', 'auyo': 'auyo', 'unik': 'unik'},
                        'babura': {'dorawa': 'dorawa', 'kyambo': 'kyambo', 'garu': 'garu', 'gasakoli': 'gasakoli', 'batali': 'batali', 
                                'kuzunzumi': 'kuzunzumi', 'takwasa': 'takwasa', 'insharuwa': 'insharuwa', 'jigawa': 'jigawa', 
                                'kanya': 'kanya', 'babura': 'babura'},
                        'birnin kudu': {'surko': 'surko', 'lafiya': 'lafiya', 'kiyako': 'kiyako', 'yalwan damai': 'yalwan damai', 
                                        'kantoga': 'kantoga', 'kwangwara': 'kwangwara', 'unguwar ya': 'unguwar ya', 'wurno': 'wurno', 
                                        'kangire': 'kangire', 'birnin kudu': 'birnin kudu', 'sundimana': 'sundimina'},
                        'birniwa': {'kachallari': 'kachallari', 'fagi': 'fagi', 'dangwaleri': 'dangwaleri', 'nguwa': 'nguwa', 'matamu': 'matamu', 
                                        'birniwa': 'birniwa', 'machinamari': 'machinamari', 'kazura': 'kazura', 'diginsa': 'diginsa', 
                                        'karanga': 'karanga', 'batu': 'batu'},
                        'buji': {'madabe': 'madabe', 'falageri': 'falgeri', 'buji': 'buji', 'ahoto': 'ahoto', 'lelen kudu': 'lelen kudu', 
                                'gantsa': 'gantsa', 'chirbin': 'chirbin', 'kawaya': 'kawaya', 'kukuma': 'kukuma', 'yayarin tukur': 'yayarin tukur'},
                        'dutse': {'chamo': 'chamo', 'limawa': 'limawa', 'dundubus': 'dundubus', 'abaya': 'abaya', 'jigawar tsada': 'jigawar tsada', 
                                'duru': 'duru', 'karnaya': 'karnaya', 'kudai': 'kudai', 'kachi': 'kachi', 'sakwaya': 'sakwaya', 'madobi': 'madobi'},
                        'gagarawa': {'yalawa': 'yalawa', 'madaka': 'madaka', 'kore balatu': 'kore balatu', 'gagarawa gari': 'gagarawa gari', 
                                'garin chiroma': 'garin chiroma', "mai'aduwa": 'mai aduwa', 'medu': 'medu', 'zarada': 'zarada', 
                                'maikilili': 'maikilili', 'gagarawa tasha': 'gagarawa tasha'},
                        'garki': {'buduru': 'buduru', 'kanya': 'kanya', 'kore': 'kore', 'rafin marke': 'rafin marke', 'jirima': 'jirima', 'sayori': 'sayori', 
                                'garki': 'garki', 'muku': 'muku', 'kargo': 'kargo', 'gwarzo': 'gwarzo', 'doko': 'doko'},
                        'gumel': {'alhaji barka': 'alhaji barka', 'garin gambo': 'garin gambo', 'kofar arewa': 'kofar arewa', 'hammado': 'hammado', 
                                'bekarya': 'bekarya', 'dan ama': 'dan ama', 'kofar yamma': 'kofar yamma', 'galagamma': 'galagamma', 
                                'zango': 'zango', 'gusau': 'gusau', 'dan tanoma': 'dantanoma'},
                        'guri': {'guri': 'guri', 'lafiya': 'lafiya', 'margadu': 'margadu', 'garbagal': 'garbagal', 'matara babba': 'matara babba', 
                                'dawa': 'dawa', 'kadira': 'kadira', 'adiyani': 'adiyani', 'abunabo': 'abunabo', 'musari': 'musari'},
                        'gwaram': {'farin dutse': 'farin dutse', 'zandam nagogo': 'zandam nagogo', 'tsangarwa': 'tsangarwa', 'maruta': 'maruta', 
                                'kila': 'kila', 'kondiko': 'kwondiko', 'dingaya': 'dingaya', 'basirka': 'basirka', 'sara': 'sara', 
                                'fagam': 'fagam', 'gwaram': 'gwaram'},
                        'gwiwa': {'firjin yamma': 'firji', 'guntai': 'guntai', 'gwiwa': 'gwiwa', 'rorau': 'rorau', 'yola': 'yola', 'korayal': 'korayel', 
                                'darina': 'darina', 'buntusu': 'buntusu', 'zauma': 'zauma', 'dabi': 'dabi', 'shafe': 'shafe'},
                        'hadejia': {'matsaro': 'matsaro', 'kasuwar kofa': 'kasuwar kofa', 'sabon garu': 'sabon garu', 'gagulmari': 'gagulmari', 
                                'atafi': 'atafi', 'dubantu': 'dubantu', 'kasuwar kuda': 'kasuwar kuda', 'yayari': 'yayari', 
                                'yankoli': 'yankoli', 'rumfa': 'rumfa'},
                        'jahun': {'kale': 'kale', 'harbo tsohuwa': 'harbo tsohuwa', 'jabarna': 'jabarna', 'idanduna': 'idanduna', 'gunka': 'gunka', 
                                'gauza': 'gauza', 'kanwa': 'kanwa', 'harbo sabuwa': 'harbo sabuwa', 'gangawa': 'gangawa', 
                                'aujara': 'aujara', 'jahun': 'jahun'},
                        'kafin hausa': {'zago': 'zago kura', 'duma dumi toka': 'dumadumi toka', 'majawa': 'majawa', 'kwazalewa': 'kwazailewa', 
                                        'gafaya': 'gafaya', 'ruba': 'ruba', 'mezan': 'mezan', 'jabo': 'jabbo', 'sarawa': 'tsarawa', 'bulangu': 'bulangu', 
                                        'kafin hausa': 'kafin hausa'},
                        'kaugama': {'hadin': 'hadin', 'jar kasa': 'girbobo', 'askandu': 'askandu', 'dabuwaran': 'dabuwaran', 'arbus': 'arbus', 'yalo': 'yalo', 
                                'kaugama': 'kaugama', 'dakayyawa': 'dakaiyyawa', 'unguwar jibrin': 'unguwar jibrin', "ja'e": 'jae', 'marke': 'marke'},
                        'kazaure': {'unguwar yamma': 'unguwar yamma', 'maradawa': 'maradawa', 'unguwar arewa': 'unguwar arewa', 'gada': 'gada', 'sabaru': 'sabaru', 
                                'daba': 'daba', 'dabaza': 'dabaza', 'unguwar gabas': 'unguwar gabas', 'dandi': 'dandi', 'kanti': 'kanti', "ba'auzini": 'baauzini'},
                        'kiri kasamma': {'madachi': 'madachi', 'bulinchai': 'bulunchai', 'saleri': 'saleri', 'gayin': 'gayin', 'marma': 'marma', 
                                        'tasheguwa': 'tasheguwa', 'turabu': 'turabu', 'kirikasamma': 'kiri kasama', 'baturiya': 'baturiya', 
                                        'fandun': 'fandum'},
                        'kiyawa': {'garko': 'garko', 'katuka': 'katuka', 'maje': 'maje', 'kwanda': 'kwanda', 'katanga': 'katanga', 'andaza': 'andaza', 
                                'tsirma': 'tsirma', 'shuwarin': 'shuwarin', 'fake': 'fake', 'balago': 'balago', 'kiyawa': 'kiyawa'},
                        'maigatari': {'fulata': 'fulata', 'dankumbo': 'dankumbo', 'madana': 'madana', 'turbus': 'turbus', 'galadi': 'galadi', 
                                'jajeri': 'jajeri', 'matoya': 'matoya', 'balarabe': 'balarabe', 'kukayasku': 'kukayasku', 'maigatari kudu': 'maigatari kudu', 
                                'maigatari arewa': 'maigatari arewa'},
                        'mallam maduri': {'shayya': 'shaiya', 'tashena': 'tashena', 'mai rakumi': 'mairakumi', 'tagwaro': 'tagoro', 'fataika': 'fateka', 
                                        'arki': 'arki', 'makaddari': 'makaddari', 'garin gabbas': 'garun gabas', 'toni kutara': 'toni kutara', 
                                        'mallam madori': 'malam madori', 'dunari': 'dunari'},
                        'miga': {'yanduna': 'yanduna', 'tsakuwawa': 'tsakuwawa', 'gwari': 'gwari', 'zareku': 'zareku', 'koya': 'koya', 'sansani': 'san sani', 
                                'hantsu': 'hantsu', 'garbo': 'garbo', 'dangytin': 'dangyatin', 'sabon gari': 'sabon gari', 'miga': 'miga'},
                        'ringim': {'karshi': 'karshi', 'dabi': 'dabi', 'kafin babushe': 'kafin babushe', 'kyarama': 'kyarama', 'tofa': 'tofa', 
                                'yan dutse': 'yandutse', 'sintilmawa': 'sintilmawa', 'sankara': 'sankara', 'chaichai': 'chaichai', 'ringim': 'ringim'},
                        'roni': {'barinje': 'dansure', 'baragumi': 'baragumi', 'sankau': 'sankau', 'kwaita': 'kwaita', 'zugai': 'zugai', 'gora': 'gora', 
                                'tunas': 'tunas', 'dansure': 'fara barije', 'yanzaki': 'yanzaki', 'amaryawa': 'amaryawa', 'roni': 'roni'},
                        'sule tankakar': {'shabaru': 'shabaru', 'danzomo': 'danzomo', 'takatsaba': 'takatsaba', 'danladi': 'danladi', 
                                        'albasu': 'albasu', 'jeke': 'jeke', 'sule tankar': 'sule tankarkar', 'yandamo': 'yandamo', 
                                        'amanga': 'amanga', 'dangwanki': 'dangwanki'},
                        'taura': {'kiri': 'kiri', 'chakwaikwaiwa': 'chukuto', 'sabon garin yaya': 'sabongarin yaya', 'maje': 'maje', 'ajaura': 'ajaura', 
                                'gujungu': 'gujungu', 'majia': 'majia', 'taura': 'taura', 'chukuto': 'chukwaikwaiwa', 'kwalam': 'kwalam'},
                        'yankwashi': {'zungumba': 'zungumba', 'belas': 'belas', 'kuda': 'kuda', 'achilafiya': 'achilafiya', 'yankwashi': 'yankwashi', 
                                'dawangawo': 'dawan gawo', 'ringim': 'ringim', 'gwarta': 'gwarta', 'karkarna': 'karkarna', 'gurjiya': 'gurjiya'},
                }

kwara_security_challenged ={"Baruten":["Yashikira",'Gure /Giwasorio'],"Edu":["Lafiagi II", "Lafiagi III"],
                            "Oke Ero":["Idofin Odo - Ashe", "Idofin Igbona II","Idofin Igbona I"],
                            "Isin":["Olla","Isanlu I","Isanlu II","Owu"], 
                            "Irepodun":["Ajase I","Ajase II","Arandun","Oro I","Esie/Ijan"],
                            "Ekiti":["Koro","Eruku","Isapa","Obbo-Ile","Obbo Aiyegunle I","Obbo Aiyegunle II"],
                            "Oyun":["Ahogbada","Igbonna","Ikotun","Ojoku","BHC ILEMONA"],
                            "Moro":["Babadudu","Bode Saadu","Ejidongari","Jehunkunu","Megida","Shao"]
                            }

# Nigeria wards boundary, lga boundary nad settlement extent from GRID3 data Hub
# dowload from this links
# https://data.grid3.org/datasets/GRID3::grid3-nga-operational-wards-v1-0/explore
# https://data.grid3.org/datasets/GRID3::grid3-nga-operational-lga-v1-0/explore
# https://data.grid3.org/datasets/GRID3::grid3-nga-settlement-extents-v2-0/explore
# https://data.grid3.org/datasets/GRID3::grid3-nga-settlement-names/explore?location=9.049179%2C8.686673%2C6.86
# extract to root directory 
# if the paths are not thesame you can change it hear
wards_shapefile ="Nigeria Wards/Nigeria_Wards.shp"
set_extent_shapefile = "Nigeria_Settlement_Extents_Version_02/nga_stlext_grid3_v02.shp"
lga_shapefile = "Nigeria_-_Local_Government_Area_Boundaries/Nigeria_-_Local_Government_Area_Boundaries.shp"
settlement_points = "Nigeria_-_Settlement_Points.csv"
